a2x: fix index out of range in exec path print
Let python format the options list, instead of iterating over it.

Fix for:
    File "/usr/lib/python3/dist-packages/asciidoc/a2x.py", line 684, in <lambda>
      ' '.join(map(lambda x: "{}{}".format(x[0], " " + x[1] if x[1] else ""), options)),
  IndexError: tuple index out of range

Example output:
  a2x: executing: asciidoc [['-f', '/usr/share/osmo-gsm-manuals/build/mscgen-filter.conf', '-f', '/usr/share/osmo-gsm-manuals/build/diag-filter.conf', '-f', '/usr/share/osmo-gsm-manuals/build/docinfo-releaseinfo.conf', '-a', "srcdir='/home/user/code/osmo-dev/src/osmo-bts/doc/manuals'", '-a', "commondir='/usr/share/osmo-gsm-manuals/common'"], ('--attribute', 'docinfo'), ('--attribute', 'revnumber=DRAFT '), ('--attribute', 'revdate=unknown'), ('--verbose',), ('--backend', 'docbook'), ('-a', 'a2x-format=pdf'), ('--out-file', '/home/user/code/osmo-dev/src/osmo-bts/doc/manuals/osmobts-usermanual.xml')]